# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    

    steps:
    # Paso 1: Checkout del código fuente
    - uses: actions/checkout@v3

    # Paso 2: Configuración del JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Paso 3: Construcción con Maven (incluye compilación y tests)
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Paso 4: Análisis estático con Checkstyle
    - name: Run Checkstyle
      run: mvn checkstyle:check

    # Paso 5: Análisis estático con SpotBugs
    - name: Run SpotBugs
      run: mvn spotbugs:spotbugs

    # Paso 6: Análisis estático con PMD
    - name: Run PMD
      run: mvn pmd:pmd

    # Paso 7: Actualización del grafo de dependencias (opcional)
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
